// frontend/src/components/SuggestionCard.vue
<template>
  <div class="suggestion-card" v-if="steps.length">
    <div class="sc-header">
      <span class="sc-title">{{ steps[current].title }}</span>
      <div class="sc-nav">
        <button class="sc-iconbtn" :disabled="current === 0" @click="prev" aria-label="Önceki">
          <ChevronLeft :size="16" />
        </button>
        <span class="sc-pager">{{ current + 1 }} / {{ steps.length }}</span>
        <button class="sc-iconbtn" @click="skip" aria-label="Sonraki">
          <ChevronRight :size="16" />
        </button>
        <button class="sc-iconbtn" @click="$emit('dismiss')" aria-label="Kapat">
          <X :size="16" />
        </button>
      </div>
    </div>

    <ul class="sc-options">
      <li v-for="(opt, i) in steps[current].options" :key="opt"
          class="sc-option" :class="{ selected: selections[steps[current].key] === opt }"
          @click="select(opt)">
        <span class="sc-num">{{ i + 1 }}</span>
        <span class="sc-label">{{ opt }}</span>
        <ArrowRight :size="16" class="sc-arrow" />
      </li>
    </ul>

    <div class="sc-footer">
      <button class="sc-skip" @click="skip">{{ isLast ? 'Bitir' : 'Atla' }}</button>
      <button class="sc-reply" @click="$emit('dismiss')">veya doğrudan yazın</button>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive, computed } from 'vue'
import { ChevronLeft, ChevronRight, ArrowRight, X } from 'lucide-vue-next'

const props = defineProps({
  clarification: { type: Object, required: true },
})
const emit = defineEmits(['apply', 'dismiss'])

// Each missing dimension becomes one step (only those with suggestions).
const STEP_DEFS = [
  { key: 'country', src: 'countries', title: 'Hangi ülke hakkında bilgi almak istiyorsunuz?' },
  { key: 'date', src: 'time_periods', title: 'Hangi zaman aralığı?' },
  { key: 'theme', src: 'themes', title: 'Hangi konu?' },
]

const steps = computed(() => {
  const s = props.clarification?.suggestions || {}
  return STEP_DEFS
    .filter(d => Array.isArray(s[d.src]) && s[d.src].length)
    .map(d => ({ key: d.key, title: d.title, options: s[d.src] }))
})

const current = ref(0)
const selections = reactive({})
const isLast = computed(() => current.value >= steps.value.length - 1)

function advance() {
  if (current.value < steps.value.length - 1) current.value++
  else finalize()
}
function select(opt) {
  selections[steps.value[current.value].key] = opt
  advance()
}
function skip() {
  advance()
}
function prev() {
  if (current.value > 0) current.value--
}
function finalize() {
  // Collect chosen values in step order and let the parent refine + re-send.
  const values = steps.value.map(s => selections[s.key]).filter(Boolean)
  if (values.length) emit('apply', values)
  else emit('dismiss')
}
</script>

<style scoped>
.suggestion-card {
  margin-top: var(--space-3);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  background: var(--color-surface);
  overflow: hidden;
}

.sc-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-3);
  padding: var(--space-3) var(--space-4);
  border-bottom: 1px solid var(--color-border);
}

.sc-title {
  font-family: var(--font-body);
  font-weight: 600;
  font-size: var(--text-sm);
  color: var(--color-text);
}

.sc-nav {
  display: flex;
  align-items: center;
  gap: var(--space-1);
  flex-shrink: 0;
}

.sc-pager {
  font-size: var(--text-xs);
  color: var(--color-muted);
  font-variant-numeric: tabular-nums;
  white-space: nowrap;
}

.sc-iconbtn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 2px;
  background: none;
  border: none;
  border-radius: var(--radius-sm);
  color: var(--color-muted);
  cursor: pointer;
  transition: color 0.15s, background-color 0.15s;
}

.sc-iconbtn:hover:not(:disabled) {
  color: var(--color-accent);
  background: var(--color-surface-container-low);
}

.sc-iconbtn:disabled {
  opacity: 0.4;
  cursor: not-allowed;
}

.sc-options {
  list-style: none;
  margin: 0;
  padding: var(--space-2);
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.sc-option {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  padding: var(--space-3);
  border-radius: var(--radius-md);
  cursor: pointer;
  transition: background-color 0.15s;
}

.sc-option:hover,
.sc-option.selected {
  background: var(--color-surface-container-low);
}

.sc-num {
  flex-shrink: 0;
  width: 22px;
  height: 22px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  font-size: var(--text-xs);
  font-weight: 600;
  color: var(--color-muted);
  background: var(--color-surface-container);
  border-radius: var(--radius-sm);
}

.sc-label {
  flex: 1;
  font-size: var(--text-sm);
  color: var(--color-text);
}

.sc-arrow {
  flex-shrink: 0;
  color: var(--color-muted);
  opacity: 0;
  transition: opacity 0.15s, color 0.15s;
}

.sc-option:hover .sc-arrow {
  opacity: 1;
  color: var(--color-accent);
}

.sc-footer {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-3);
  padding: var(--space-1) var(--space-4) var(--space-3);
}

.sc-skip {
  background: none;
  border: 1px solid var(--color-border);
  border-radius: var(--radius-full);
  padding: var(--space-1) var(--space-4);
  font-family: var(--font-body);
  font-size: var(--text-xs);
  color: var(--color-text);
  cursor: pointer;
  transition: border-color 0.15s, color 0.15s;
}

.sc-skip:hover {
  border-color: var(--color-accent);
  color: var(--color-accent);
}

.sc-reply {
  background: none;
  border: none;
  font-family: var(--font-body);
  font-size: var(--text-xs);
  color: var(--color-muted);
  cursor: pointer;
  text-decoration: underline;
}

.sc-reply:hover {
  color: var(--color-accent);
}
</style>

// frontend/src/components/react/SuggestionCard.jsx
import { useState, useRef, useEffect, useMemo } from 'react'
import { ChevronLeft, ChevronRight, ArrowRight, X, Check } from 'lucide-react'
import './SuggestionCard.css'

// Each missing query dimension becomes one step (only those with suggestions).
const STEP_DEFS = [
  { key: 'country', src: 'countries', title: 'Hangi ülke hakkında bilgi almak istiyorsunuz?', placeholder: 'veya bir ülke yazın…' },
  { key: 'date', src: 'time_periods', title: 'Hangi zaman aralığı?', placeholder: 'veya zaman aralığı yazın…' },
  { key: 'theme', src: 'themes', title: 'Hangi konu?', placeholder: 'veya bir konu yazın…' },
]

/**
 * Multi-step suggestion card (React island).
 * Options are shown as side-by-side wrapping chips; the user can also type a
 * custom answer for the current step. Props:
 *   clarification: { suggestions: { countries, time_periods, themes } }
 *   onApply: (values: string[]) => void   // chosen values in step order
 *   onDismiss: () => void
 */
export default function SuggestionCard({ clarification, onApply, onDismiss }) {
  const steps = useMemo(() => {
    const s = clarification?.suggestions || {}
    return STEP_DEFS
      .filter((d) => Array.isArray(s[d.src]) && s[d.src].length)
      .map((d) => ({ key: d.key, title: d.title, placeholder: d.placeholder, options: s[d.src] }))
  }, [clarification])

  const [current, setCurrent] = useState(0)
  const [selections, setSelections] = useState({})
  const [custom, setCustom] = useState('')
  const firstOptRef = useRef(null)

  // On each step, clear the typed value and move focus to the first chip.
  useEffect(() => {
    setCustom('')
    firstOptRef.current?.focus({ preventScroll: true })
  }, [current])

  if (!steps.length) return null
  const step = steps[current]
  const isLast = current >= steps.length - 1

  function finalize(next) {
    const values = steps.map((s) => next[s.key]).filter(Boolean)
    if (values.length) onApply(values)
    else onDismiss()
  }
  function advance(next) {
    if (current < steps.length - 1) setCurrent((c) => c + 1)
    else finalize(next)
  }
  function select(opt) {
    const v = (opt || '').trim()
    if (!v) return
    const next = { ...selections, [step.key]: v }
    setSelections(next)
    advance(next)
  }
  function skip() { advance(selections) }
  function prev() { if (current > 0) setCurrent((c) => c - 1) }

  function submitCustom(e) {
    e.preventDefault()
    select(custom)
  }
  function onKeyDown(e) {
    // Keep it simple and conflict-free with the text input: Esc dismisses;
    // chips are native buttons (Enter/Space/click) and the input owns its keys.
    if (e.key === 'Escape') { e.preventDefault(); onDismiss() }
  }

  const chosen = steps.map((s) => selections[s.key]).filter(Boolean)

  return (
    <div
      className="sc-card"
      role="group"
      aria-label="Sorgunuzu detaylandırma önerileri"
      onKeyDown={onKeyDown}
    >
      <div className="sc-header">
        <span className="sc-title" aria-live="polite">{step.title}</span>
        <div className="sc-nav">
          <span className="sc-dots" aria-hidden="true">
            {steps.map((_, i) => (
              <span key={i} className={'sc-dot' + (i === current ? ' active' : i < current ? ' done' : '')} />
            ))}
          </span>
          <span className="sc-hint">{current + 1} / {steps.length}</span>
          <button className="sc-iconbtn" onClick={prev} disabled={current === 0} aria-label="Önceki adım">
            <ChevronLeft size={16} />
          </button>
          <button className="sc-iconbtn" onClick={skip} aria-label="Sonraki adım">
            <ChevronRight size={16} />
          </button>
          <button className="sc-iconbtn" onClick={onDismiss} aria-label="Önerileri kapat">
            <X size={16} />
          </button>
        </div>
      </div>

      {chosen.length > 0 && (
        <div className="sc-chips">
          {chosen.map((v) => (
            <span className="sc-chip" key={v}><Check size={12} />{v}</span>
          ))}
        </div>
      )}

      <div className="sc-options" role="radiogroup" aria-label={step.title} key={current}>
        {step.options.map((opt, i) => (
          <button
            key={opt}
            ref={i === 0 ? firstOptRef : undefined}
            type="button"
            className="sc-opt"
            style={{ '--i': i }}
            role="radio"
            aria-checked={selections[step.key] === opt}
            onClick={() => select(opt)}
          >
            {opt}
          </button>
        ))}
      </div>

      <form className="sc-input-row" onSubmit={submitCustom}>
        <input
          className="sc-input"
          type="text"
          value={custom}
          onChange={(e) => setCustom(e.target.value)}
          placeholder={step.placeholder}
          aria-label={step.placeholder}
        />
        <button className="sc-input-go" type="submit" disabled={!custom.trim()} aria-label="Yazdığını kullan">
          <ArrowRight size={16} />
        </button>
      </form>

      <div className="sc-footer">
        <button className="sc-skip" onClick={skip}>{isLast ? 'Bitir' : 'Atla'}</button>
      </div>
    </div>
  )
}
